<div class="row">
    <div class="col-md-4">
        <div class="well">
            <?php foreach($this->dates_filter as $year => $year_list): ?>
                <div class="year_option">
                    <span><a href="<?php echo $this->url('home').'?'.http_build_query(['year'=> $year, 'theme_id' => $this->filter_options['theme_id']]) ?>"><?php echo $year; ?></a></span>
                    <ul>
                        <?php foreach($year_list as $month): ?>
                            <li>
                                <a href="<?php echo $this->url('home').'?'.http_build_query(['year'=>$year, 'month'=>$month["month"], 'theme_id' => $this->filter_options['theme_id']]) ?>"><?php echo $this->month_names[$month["month"]-1]; ?></a>
                                <b>(<?php echo $month['count']; ?>)</b>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="well">
            <?php foreach($this->themes_filter as $theme): ?>
                <div class="year_option">
                    <span><a href="<?php echo $this->url('home').'?'.http_build_query(['year'=>$this->filter_options['year'], 'month'=>$this->filter_options['month'],'theme_id' =>$theme['theme_id']]); ?>"><?php echo $theme['theme_title']; ?></a></span>
                    <b>(<?php echo $theme['count']; ?>)</b>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-md-8">
        <?php foreach($this->paginator as $item): ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <?php echo $item['title']?>
                    </h3>
                    <div>
                        <?php echo $item['date']?> -
                        <?php echo $item['theme_title']?>
                    </div>
                </div>
                <div class="panel-body">
                    <?php echo $item['text']?>
                </div>
            </div>
        <?php endforeach;?>
        <?php echo $this->paginationControl($this->paginator,
            'Sliding',
            'partial/pagination_control.phtml', array('route' => 'presenter/paginator'));
        ?>
    </div>
</div>
