<div class="row">
    <div class="col-md-4">
        <div class="well">
            <?php foreach($this->dates_filter as $year => $year_list): ?>
                <div class="year_option">
                    <span><?php echo $year; ?></span>
                    <ul>
                        <?php foreach($year_list as $month): ?>
                            <li>
                                <?php echo $this->month_names[$month["month"]-1]; ?>
                                <b>(<?php echo $month['count']; ?>)</b>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="well">
            <?php foreach($this->themes_filter as $theme): ?>
                <div class="year_option">
                    <span><a href="<?php echo $this->url('home').'?'.'theme_id='.$theme['theme_id'] ?>"><?php echo $theme['theme_title']; ?></a></span>
                    <b>(<?php echo $theme['count']; ?>)</b>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-md-8">
        <?php foreach($this->list as $item): ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <?php echo $item['title']?>
                    </h3>
                    <div>
                        <?php echo $item['date']?> -
                        <?php echo $item['theme_title']?>
                    </div>
                </div>
                <div class="panel-body">
                    <?php echo $item['text']?>
                </div>
            </div>
        <?php endforeach;?>
    </div>
</div>
